import express from "express";
import pg from "pg";
import Stripe from "stripe";
import crypto from "crypto";

const app=express();const port=process.env.PORT||3000;
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes("localhost")?false:{rejectUnauthorized:false}});
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const services={"hedge-trimming":["Hedge trimming",35],"flower-bed-weeding":["Flower-bed weeding",30],"leaf-cleanup":["Leaf cleanup",45],"lawn-fertilization":["Lawn fertilization",40],"sprinkler-inspection":["Sprinkler inspection",49],"debris-haul-away":["Debris haul-away",75]};
const slots=["Morning","Afternoon"];
const firstMowSpecialEndsAt=new Date("2026-09-02T05:00:00.000Z");

async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS bookings(id text primary key,stripe_session_id text,status text not null,name text not null,email text not null,phone text not null,address text not null,city text not null,zip text not null,appointment_date date not null,appointment_time text not null,lawn_size integer not null,frequency text not null,amount_cents integer not null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());CREATE UNIQUE INDEX IF NOT EXISTS bookings_slot_unique ON bookings(appointment_date,appointment_time);CREATE TABLE IF NOT EXISTS availability_blocks(id serial primary key,appointment_date date not null,appointment_time text not null,unique(appointment_date,appointment_time));`)}
function firstMowSpecialIsActive(now=new Date()){return now<firstMowSpecialEndsAt}
function mowing(size,frequency,overgrown){const base=size===3500?45:size===6500?55:size===10000?70:0;const regular=firstMowSpecialIsActive()?33:frequency==="weekly"?Math.max(40,base-5):base;return overgrown?Math.ceil(regular*1.5/5)*5:regular}
function admin(req,res,next){if(req.headers.authorization===`Bearer ${process.env.ADMIN_PASSWORD}`)return next();res.status(401).set("WWW-Authenticate",'Basic realm="Lawn Blvd Calendar"').send("Use your admin password as the password. Username can be anything.")}

app.post("/api/stripe/webhook",express.raw({type:"application/json"}),async(req,res)=>{try{const event=stripe.webhooks.constructEvent(req.body,req.headers["stripe-signature"],process.env.STRIPE_WEBHOOK_SECRET);const id=event.data.object.metadata?.booking_id;if(id&&event.type==="checkout.session.completed")await pool.query("UPDATE bookings SET status='paid' WHERE id=$1",[id]);if(id&&event.type==="checkout.session.expired")await pool.query("DELETE FROM bookings WHERE id=$1 AND status='pending'",[id]);res.json({received:true})}catch(e){res.status(400).send(`Webhook error: ${e.message}`)}});
app.use(express.json());app.use(express.static("public"));
app.get("/api/availability",async(req,res)=>{await pool.query("DELETE FROM bookings WHERE status='pending' AND created_at<now()-interval '30 minutes'");const used=await pool.query("SELECT appointment_date::text,appointment_time FROM bookings WHERE appointment_date>=current_date UNION SELECT appointment_date::text,appointment_time FROM availability_blocks WHERE appointment_date>=current_date");const taken=new Set(used.rows.map(r=>`${r.appointment_date}|${r.appointment_time}`));const out=[];const d=new Date();for(let i=0;i<30;i++){const date=d.toISOString().slice(0,10);if(d.getDay()!==0)for(const time of slots)out.push({date,time,label:d.toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"}),available:!taken.has(`${date}|${time}`)});d.setDate(d.getDate()+1)}res.json({slots:out})});
app.post("/api/checkout",async(req,res)=>{let id;try{if(!stripe)return res.status(503).json({error:"Stripe is not connected yet."});const p=req.body;for(const key of ["name","email","phone","address","city","zip","appointmentDate","appointmentTime"])if(!String(p[key]||"").trim())return res.status(400).json({error:"Please complete every required field."});const frequency=p.frequency==="weekly"?"weekly":"biweekly";const mow=mowing(Number(p.size),frequency,Boolean(p.overgrown));const addOns=[...new Set(Array.isArray(p.addOns)?p.addOns:[])].map(x=>services[x]&&{id:x,name:services[x][0],price:services[x][1]}).filter(Boolean);const total=mow+addOns.reduce((a,x)=>a+x.price,0);id=crypto.randomUUID();await pool.query("INSERT INTO bookings(id,status,name,email,phone,address,city,zip,appointment_date,appointment_time,lawn_size,frequency,amount_cents,details) VALUES($1,'pending',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)",[id,p.name,p.email,p.phone,p.address,p.city,p.zip,p.appointmentDate,p.appointmentTime,p.size,frequency,total*100,{gate:p.gate||"",notes:p.notes||"",overgrown:!!p.overgrown,addOns}]);const origin=process.env.PUBLIC_URL||`${req.protocol}://${req.get("host")}`;const line_items=[{price_data:{currency:"usd",unit_amount:mow*100,product_data:{name:"Lawn Blvd — First Mow"}},quantity:1},...addOns.map(x=>({price_data:{currency:"usd",unit_amount:x.price*100,product_data:{name:`Lawn Blvd — ${x.name}`}},quantity:1}))];const session=await stripe.checkout.sessions.create({mode:"payment",customer_email:p.email,line_items,success_url:`${origin}/success.html?booking=${id}`,cancel_url:`${origin}/`,metadata:{booking_id:id},payment_intent_data:{metadata:{booking_id:id}},phone_number_collection:{enabled:true}});await pool.query("UPDATE bookings SET stripe_session_id=$1 WHERE id=$2",[session.id,id]);res.json({url:session.url})}catch(e){if(id)await pool.query("DELETE FROM bookings WHERE id=$1 AND status='pending'",[id]);res.status(409).json({error:e.code==="23505"?"That time was just booked. Choose another.":"Checkout could not start."})}});
app.get("/api/admin/bookings",admin,async(req,res)=>{const q=await pool.query("SELECT * FROM bookings WHERE appointment_date>=current_date ORDER BY appointment_date,appointment_time");res.json(q.rows)});
app.post("/api/admin/block",admin,async(req,res)=>{const{date,time,blocked}=req.body;if(blocked)await pool.query("INSERT INTO availability_blocks(appointment_date,appointment_time) VALUES($1,$2) ON CONFLICT DO NOTHING",[date,time]);else await pool.query("DELETE FROM availability_blocks WHERE appointment_date=$1 AND appointment_time=$2",[date,time]);res.json({ok:true})});
init().then(()=>app.listen(port,"0.0.0.0",()=>console.log(`Lawn Blvd running on ${port}`))).catch(e=>{console.error(e);process.exit(1)});
